{% set version = "0.3.0" %}

package:
  name: docker-pycreds
  version: {{ version }}

source:
  fn: docker-pycreds-{{ version }}.tar.gz
  url: https://github.com/shin-/dockerpy-creds/archive/{{ version }}.tar.gz
  sha256: 3660a5e9fc7c2816ab967e4bdb4802f211e35011357ae612a601d6944721e153

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - six >=1.4.0
  run:
    - python
    - six >=1.4.0

test:
  imports:
    - dockerpycreds

about:
  home: https://github.com/shin-/docker-pycreds/
  license: Apache-2.0
  summary: 'Python bindings for the docker credentials store API'
  license_file: LICENSE
  license_family: Apache

extra:
  recipe-maintainers:
    - ocefpaf
    - scopatz
