{% set version = "0.2.3" %}

package:
  name: docker-pycreds
  version: {{ version }}

source:
  fn: docker-pycreds-{{ version }}.tar.gz
  url: https://github.com/shin-/dockerpy-creds/archive/{{ version }}.tar.gz
  sha256: 7278a7e3c904ccea4bcc777b991a39cac9d4702bfd7d76b95ff6179500d886c4

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - six >=1.4.0
  run:
    - python
    - six >=1.4.0

test:
  imports:
    - dockerpycreds

about:
  home: https://github.com/shin-/docker-pycreds/
  license: Apache-2.0
  summary: 'Python bindings for the docker credentials store API'
  license_file: LICENSE
  license_family: Apache

extra:
  recipe-maintainers:
    - ocefpaf
    - scopatz
