travis:
  secure:
    BINSTAR_TOKEN: PyF3EwgYagJkSIw5C6Gohrym638nlxQu4TY0nVMZqAfEA5pfFvbGyzThtUJ7woiw2ipxSp9RnDhNLndQO8FqiSkYZr5HiIboZZb4qpK6lr67bNb7DtiAZF3nN+d1Z2cL4lqu8HGOpAcTc/WV+cdsY6Rl9CkV6qK5OHePrkTyU5MsGRWDyA4iJx+ZsngmIkO5ZSWsj/uOH2UW4gvGyg9ouOh9E5nIMzPVH1NvrddBHNrZzmtmozDoNx6i3w8UO2aGytQnVEtV+PkOO3KC91N9fpVAjoy7B/APcn12tEcyB905rRUpaItRaCvkC4Fl4J0rz34IiOCw/8ATmaWuO0qOtkCLYYQlWfCtwN4ZOIPlb0pqriQ0ITGAy+uZkG+OCi4Ax9SP8x8IR3LuGMCGqXoG5g7epd5+ysoq+RFPRtEUTYIy3IWOsLuyuQlIu8Hlt0bTQ+s5d9KtIAUO4r0isqEuCmapeh7qg+qdqev6t3YKzIumD+myEOSSiaeVg3l37mnMv2b7/KlIdsm3pxDZv6rxMnGfDsUp0Wvwm8NM0ncfYs8Q+hmIbT6TFbPu3KeHvDPvIs7PA7d/wRXvTRammEivTi33sbvc8/FwVOJpiedgsHmLjbQBSPns2CEa62LTY5caJYPVU9ppZOOnNYue468tEL1EnnNgbpK/6a2Qu/q4jPc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
