travis:
  secure:
    BINSTAR_TOKEN: fjdSJ9VCgLXO8W4fcVcMro40C06v3mfafevAX4JhBd9AcRV6nB8HyrhaJToWRWPR0Jbx+IjR3ZIXwtshwlaWDP7klfPXjQ1uajxv5qyXKlaHq9DVypN6Z+mu+Voo3rxAAKLndc0cNMHW/KCAfxOgE2efd9baaPeVAPTYm+M6HB51LXGdfLMXv2vTLKI3NrVmeWPJEGj+t24CnYDccb9h9PBisSXfUGl4KCBh0UdZ07M2q7ixceHkMsTrTNCHTIZk9/wC6tMbFewEu9O5spn0CTS8sMDeSxjigmm7LoMnrk9MUZf2ij2208eLAbDeH9Y3N6CmSNmeibha3eN+VsP7pWRqksDD1Y8UqO1QLb758ZpF4bZCxyzf0njnDdA2VC2Ihsj7pQZI7RMewv0+Cmw3xpgZ/VBcA9VvJoHJdwMwvOlVrNZQRM9LgnD1/TcgVB0LMvOHPZ2eSx4sB3JXK7N0yhXCjULfA1U7maWykRWXejhsJWlGazb+F36GRxGJQkE+MBfj5xMwh/7BgbAQ2YQjiJSBuZe7GPB7ou1fd4/mnUjMVTLVPw8LBP0ATkWmRRlSXbSY4fmNDnjHuXTTNmoKGjeAWKyY3PWx3sEDR+PM6DaUTRw/XLyA7NtxyCBhK20DkBLO1p6JA0PYL4CU1Uujqcze9r4a5m36y6SH1HWWs40=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
